apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-username>/aks-helm-argocd-demo.git
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
