apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/avadhutpatil22/aks-helm-argocd-demo-2025.git
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
